# [ENV: CartPole-v0]
# ENVIRONMENT_ID = "CartPole-v0"
# ENV_RENDER = False
# WIN_AND_LEARN_FINISH_SCORE = 195
# WIN_AND_LEARN_FINISH_CONTINUOUS_EPISODES = 100

#[ENV: RoboschoolAnt-v1]
# ENVIRONMENT_ID = "RoboschoolAnt-v1"
# ENV_RENDER = False
# WIN_AND_LEARN_FINISH_SCORE = 1500
# WIN_AND_LEARN_FINISH_CONTINUOUS_EPISODES = 10

# [ENV: RoboschoolAnt-v1]
ENVIRONMENT_ID = "Quanser_Servo_2"
ENV_RENDER = False
WIN_AND_LEARN_FINISH_SCORE = 100
<<<<<<< HEAD
WIN_AND_LEARN_FINISH_CONTINUOUS_EPISODES = 5
=======
WIN_AND_LEARN_FINISH_CONTINUOUS_EPISODES = 5

>>>>>>> 3df34e98baf7b915e44384f554bb0c75c782efce
